export const ActionTypes = {
    SET_IMAGES: "SET_IMAGES",
    APPEND_IMAGES: "APPEND_IMAGES",
    SELECTED_IMAGE: "SELECTED_IMAGE",
    RESET_STORE: "RESET_STORE",
    SET_ALL_IMAGES_PAYLOAD: "SET_ALL_IMAGES_PAYLOAD",
  };

