import Head from 'next/head'
import styles from '../styles/layout.module.css'
import SearchBar from '../components/SearchBar'


export default function Home() {

 
return (
    <div className="container">
      <Head>
          <title>Shutter Up</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h3 className={styles.styling}>Here you can find images around the world</h3>
       
        <SearchBar/>

    </div>
  )
}
